version: "3"

services:
  python:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - USERNAME=${USERNAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    volumes:
      - ../:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    shm_size: "2gb"
    tty: true
